services:
  db:
    image: mongo:7.0.15
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]

  web:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
     test: ["CMD", "python3", "-c", "import socket; s = socket.socket(); s.connect(('localhost', 8000))"]
     interval: 10s
     timeout: 5s
     retries: 5

  simulator:
    build:
      context: .
      dockerfile: src/bot/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      - API_URL=http://web:8000/api
    depends_on:
      web:
        condition: service_healthy

volumes:
  mongo_data:
